const actionTypes = {
	MAKES_LOAD_START: "MAKES_LOAD_START",
	MAKES_LOAD_SUCCESS: "MAKES_LOAD_SUCCESS",
	MAKES_LOAD_ERROR: "MAKES_LOAD_ERROR",

	MODELS_LOAD_START: "MODELS_LOAD_START",
	MODELS_LOAD_SUCCESS: "MODELS_LOAD_SUCCESS",
	MODELS_LOAD_ERROR: "MODELS_LOAD_ERROR",

	VEHICLES_LOAD_START: "VEHICLES_LOAD_START",
	VEHICLES_LOAD_SUCCESS: "VEHICLES_LOAD_SUCCESS",
	VEHICLES_LOAD_ERROR: "VEHICLES_LOAD_ERROR",
};

export default actionTypes;